import { Manrope, Prompt, Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const manropeFont = Manrope({
  variable: "--font-number",
  subsets: ["latin"],
})

const promptFont = Prompt({
  variable: "--font-heading",
  weight: "700",
  subsets: ["latin"],
});

const interFont = Inter({
  variable: "--font-text",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manropeFont.variable} ${promptFont.variable} ${interFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
